### ISSUE TITLE
No password strength checking on password change

### ISSUE THREAD

**Issue by 4855062503** [zap-me/alloy#10]
Not sure on the severity of this issue since we already have email 2FA.

Steps to reproduce:

Go to alloy, sign in, and then attempt to change your password to a one or two character password.

I was able to successfully.

**Comment by djpnewton** [comment]
make a PR?

**Comment by 4855062503** [comment]
Should I make a zapdart PR for front-end password form validation here?

https://github.com/zap-me/zapdart/blob/master/lib/account_forms.dart

So that the `currentPassword` validator on line 479 checks if the password is the desired length or contains uppercase or special characters?

**Comment by 4855062503** [comment]
Could use this package for front-end updatePassword form validation:

https://pub.dev/packages/zxcvbn

**Comment by djpnewton** [comment]
I think this was implemented
