### ISSUE TITLE
2FA mailer for gmail goes to Spam folder until marked as non-spam

### ISSUE THREAD

**Issue by 4855062503** [zap-me/alloy#11]
Probably nothing we can do about this but suggest to the new user to check their spam folder?

**Comment by djpnewton** [comment]
use a service like https://www.mail-tester.com/ to see what is causing our email to look like spam

**Comment by djpnewton** [comment]
@4855062503 did you try mail-tester.com to see what the issue could be?

**Comment by 4855062503** [comment]
Works on mail-tester.com

However, we only scored 8.5/10 as we are listed in 2 blacklists as spam:

- [Hostkarma](http://ipadmin.junkemailfilter.com/remove.php)
- [SORBS (last 28 days)](http://ipadmin.junkemailfilter.com/remove.php)

**Comment by djpnewton** [comment]
which host? can you submit the IP for removal then?

**Comment by 4855062503** [comment]
@djpnewton 
https://www.mail-tester.com/test-3t1s4ne87

**Comment by djpnewton** [comment]
ok that is beryllium-test now do prod

**Comment by djpnewton** [comment]
will need to retest once https://github.com/zap-me/ops/issues/154 goes in
