### ISSUE TITLE
Getting "failed to query deposit address" popup when attempting to do a cryptocurrency deposit

### ISSUE THREAD

**Issue by 4855062503** [zap-me/alloy#12]
Not sure if something to do with deposits being intentionally down:

Steps to reproduce:

Sign in to Alloy then go to the deposits page, click any cryptocurrency then press the '+' button.

**Comment by eoliveros** [comment]
this could be related to this:
-------------------------------
So here are the three (!) outstanding dasset errors that I am waiting for advise on:
:: confirming withdrawals

app_1  | [dasset INFO] POST - https://api.dassetx.com/api/crypto/withdrawals/confirm
app_1  | [dasset INFO] HEADERS - {'x-api-key': 'xxxxx', 'x-account-id': '9cc6b4c4-2116-47dc-a997-40dcdcc06949'}
app_1  | [dasset INFO] PARAMS - {'txId': '8abec9da-70a2-4654-a744-a0c4b812dbd7', 'token': '676871'}
app_1  | [dasset ERROR] request failed: 500, b'{"status":500,"type":"Server error","code":"NotAuthorizedException","message":"Invalid Access Token"}'



:: querying deposits

app_1  | [dasset INFO] GET - https://api.dassetx.com/crypto/deposits/open
app_1  | [dasset INFO] HEADERS - {'x-api-key': 'xxxxx', 'x-account-id': '9cc6b4c4-2116-47dc-a997-40dcdcc06949', 'x-subaccount-id': 'e4e61960-e415-40ab-857b-db6a4949e1dc'}
app_1  | [dasset ERROR] request failed: 403, b'{"message":"Missing Authentication Token"}'

app_1  | [dasset INFO] GET - https://api.dassetx.com/crypto/deposits/closed
app_1  | [dasset INFO] HEADERS - {'x-api-key': 'xxxxx', 'x-account-id': '9cc6b4c4-2116-47dc-a997-40dcdcc06949', 'x-subaccount-id': 'e4e61960-e415-40ab-857b-db6a4949e1dc'}
app_1  | [dasset ERROR] request failed: 403, b'{"message":"Missing Authentication Token"}'



:: transferring funds from sub account to master account

app_1  | [dasset INFO] HEADERS - {'x-api-key': 'xxxxx', 'x-account-id': '9cc6b4c4-2116-47dc-a997-40dcdcc06949', 'x-subaccount-id': 'e4e61960-e415-40ab-857b-db6a4949e1dc'}
app_1  | [dasset INFO]    POST - https://api.dassetx.com/api/transfer
app_1  | [dasset ERROR] request failed: 403, b'{"status":403,"type":"Forbidden","code":4032,"message":"Insufficient permissions - user missing route permission"}'

**Comment by 4855062503** [comment]
That makes sense.

**Comment by djpnewton** [comment]
yes this is an issue at dasset

**Comment by djpnewton** [comment]
solved now i guess
