### ISSUE TITLE
Can't use dart:html for iOS builds

### ISSUE THREAD

**Issue by 4855062503** [zap-me/alloy#14]
[Related](https://stackoverflow.com/questions/60646793/avoid-using-web-only-libraries-outside-flutter-web-plugin-packages)

Upon running a build for iOS on a factory-reset Mac I get:

```
    import 'dart:html' as html;
           ^
    lib/main.dart:162:29: Error: Undefined name 'window'.
                if (value) html.window.location.reload();
```

[This](https://github.com/zap-me/alloy/blob/ca909dabd53ecc5a9dcc4cf9c6fc1a4ab888a270/lib/main.dart#L162) looks like the only place its used so perhaps we could use a cross-platform alternative package?

**Comment by djpnewton** [comment]
try using this https://pub.dev/packages/universal_html

**Comment by 4855062503** [comment]
> try using this https://pub.dev/packages/universal_html

Just did and it worked good. Should I make a PR?
