### ISSUE TITLE
Getting form validation error "invalid address version" for valid Litecoin addresses in LTC-NZD market

### ISSUE THREAD

**Issue by 4855062503** [zap-me/alloy#9]
Not sure if this is just something to do with not supporting legacy addresses.

Steps to reproduce:

Click Markets -> LTC-NZD -> Enter "MTvnA4CN73ry7c65wEuTSaKzb2pNKHB4n1" as the Wallet Address -> attempt Create Order

**Comment by djpnewton** [comment]
old
